### ISSUE TITLE
Make wallet-provider Release Ready

### ISSUE THREAD

**Issue by Elli610** [massalabs/wallet-provider#78]
# Objective
The purpose of this issue is to ensure that the library is updated to meet the expected criteria for an application to be maintained and considered release-ready. The requirements are outlined in the Run team procedure: [Definition of Release-Ready](https://www.notion.so/massa-innoteam/Definition-of-Release-Ready-964a4f2ffd9549129edf76d6c623c490).

# Missing features
- [x] Add sendTransaction to Account and MassaStationAccount objects
- [ ] Add deploySC to Account and MassaStationAccount objects

# Documentation:

## Git documentation

- [x] #155
- [ ] improve, update or add CONTRIBUTING.md
- [ ] improve, update or add license.md
- [ ] improve, update or add USAGE.md

### Account documentation

- [x] #160
- [x] #162
- [x] #164
- [x] #166
- [x] #170
- [x] #169
- [x] #171
- [x] improve or add documentation for src/account/IAccountSendTransaction.ts
- [x] improve or add documentation for src/account/INonPersistantExecution.ts
- [ ] improve or add documentation for src/account/index.ts

### Connector documentation

- [x] #174
- [ ] improve or add documentation for src/connector/ICustomEventMessageRequest.ts
- [ ] improve or add documentation for src/connector/ICustomEventMessageResponse.ts
- [ ] improve or add documentation for src/connector/IRegisterEvent.ts
- [ ] improve or add documentation for src/connector/index.ts

### MassaStation documentation

- [ ] improve or add documentation for src/massaStation/MassaStationAccount.ts
- [ ] improve or add documentation for src/massaStation/MassaStationDiscovery.ts
- [ ] improve or add documentation for src/massaStation/MassaStationProvider.ts
- [ ] improve or add documentation for src/massaStation/RequestHandler.ts

### Provider documentation

- [ ] improve or add documentation for src/provider/AccountDeletion.ts
- [ ] improve or add documentation for src/provider/AccountImport.ts
- [ ] improve or add documentation for src/provider/AccountGeneration.ts
- [ ] improve or add documentation for src/provider/IProvider.ts
- [ ] improve or add documentation for src/provider/Provider.ts
- [ ] improve or add documentation for src/provider/index.ts
- [ ] improve or add documentation for src/utils/argsToBase64.ts
- [ ] improve or add documentation for src/utils/time.ts

### ./src documentation

- [ ] improve or add documentation for src/index.ts

# Testing

- [ ] Test src/account/Account.ts
- [ ] Test src/massaStation/MassaStationAccount.ts
- [ ] Test src/massaStation/MassaStationProvider.ts 
- [ ] Test Test src/provider/Provider.ts

# Security

- [ ]  Define a security model
- [ ]  Implement proper countermeasures, such as static analysis of code and security checks of dependencies

# Automation

- [ ]  Automate tasks that can be automated

## Wrap Up

- [ ]  Ensure that the Run team procedure was properly applied and update the document if necessary
- [ ]  Communicate that the library is now considered release-ready
