### ISSUE TITLE
tasks to integrate bearby

### ISSUE THREAD

**Issue by Elli610** [massalabs/wallet-provider#93]
ALL CHANGES HAVE TO BE DONE FROM THE FOLLOWING BRANCH: 90-integrate-bearby-wallet-in-wallet-provider

related to https://github.com/massalabs/wallet-provider/issues/90

Priority:
- [x] see if bearby can allow us to broadcast tx through their wallet. Otherwise we'll have to hardcode a nodeUrl and won't be able to switch between buildnet and testnet without rebuilding the package
- [ ] #94
- [x] find a way to get all the arguments in a Args object to use them with bearby call function
- adapt all functions related to the non persistent execution
- find a way to detect if bearby is installed without triggering web3.wallet.connect() -> then implement it in the connector (where the "check if bearby is installed" comment is located)

non urgent:
- [x] test buy and sell rolls function
- [x] test sendTransaction
- [x] test callSC
- [x] test balance
